name: maidstest
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  modal_progress_hud_nsn: ^0.5.1
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  rflutter_alert: ^2.0.7
  flutter_overlay_loader: ^2.0.0
  animated_snack_bar: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: HB
      fonts:
        - asset: assets/font/Helvetica-Bold.ttf

    - family: H
      fonts:
        - asset: assets/font/Helvetica.ttf
  #
